services:
  docker1:
    build: ./docker1
    ports:
      - "5002:5000"
    depends_on:
      - docker2
    networks:
      - backend
  
  docker2:
    build:
      ./docker2
    depends_on:
      - docker3
    networks:
      - backend

  docker3:
    build: ./docker3
    ports:
      - "5001:5000"
    networks:
      - backend
  
  docker4:
    build: ./docker4
    networks:
      - backend
    depends_on:
      - redis
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  flower:
    image: mher/flower
    command: celery --broker=redis://redis:6379/0 flower
    ports:
      - "5555:5555"
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  redis-data: